name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: maven test
        uses: mvn text
        
      - name: checkstyle test
        uses: mvn checkstyle:checkstyle



